name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened and what did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal steps/commands to reproduce
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node, Docker, DB versions
  - type: textarea
    id: logs
    attributes:
      label: Logs / stacktrace
      render: shell


