name: Feature request
description: Propose an improvement or new capability
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem or use case motivates this?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior / API / UI
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: input
    id: context
    attributes:
      label: Context
      placeholder: Links / related issues


